import subprocess

names = [
    'furHelmet',
    'furChestplate',
    'furLeggings',
    'furBoots',
    'chainHelmet',
    'chainChestplate',
    'chainBoots',
    'iron_01_Helmet',
    'iron_01_Chestplate',
    'iron_01_Leggings',
    'iron_01_Boots',
    'iron_02_Helmet',
    'iron_02_Chestplate',
    'iron_02_Leggings',
    'iron_02_Boots',
    'iron_03_Helmet',
    'iron_03_Chestplate',
    'iron_03_Leggings',
    'iron_03_Boots',
    'iron_04_Helmet',
    'iron_04_Chestplate',
    'iron_04_Leggings',
    'iron_04_Boots',
    'iron_Helmet',
    'iron_Chestplate',
    'iron_Leggings',
    'iron_Boots',
    'leatherHelmet',
    'leatherChestplate',
    'leatherLeggings',
    'leatherBoots',
    'mithrilHelmet',
    'mithrilChestplate',
    'mithrilBoots',
    'rawhideHelmet',
    'rawhideChestplate',
    'rawhideLeggings',
    'rawhideBoots',
    'robe_01_Helmet',
    'robe_01_Chestplate',
    'robe_01_Leggings',
    'robe_01_Boots',
    'robe_02_Helmet',
    'robe_02_Chestplate',
    'robe_02_Leggings',
    'robe_02_Boots',
    'robe_03_Helmet',
    'robe_03_Chestplate',
    'robe_03_Leggings',
    'robe_03_Boots',
    'robe_04_Helmet',
    'robe_04_Chestplate',
    'robe_04_Leggings',
    'robe_04_Boots',
    'robe_05_Helmet',
    'robe_05_Chestplate',
    'robe_05_Leggings',
    'robe_05_Boots',
    'clothes_01_Helmet',
    'clothes_01_Chestplate',
    'clothes_01_Leggings',
    'clothes_01_Boots',
    'clothes_02_Helmet',
    'clothes_02_Chestplate',
    'clothes_02_Leggings',
    'clothes_02_Boots',
    'clothes_03_Helmet',
    'clothes_03_Chestplate',
    'clothes_03_Leggings',
    'clothes_03_Boots',
    'clothes_04_Helmet',
    'clothes_04_Chestplate',
    'clothes_04_Leggings',
    'clothes_04_Boots',
    'clothes_05_Helmet',
    'clothes_05_Chestplate',
    'clothes_05_Leggings',
    'clothes_05_Boots',
    'clothes_06_Helmet',
    'clothes_06_Chestplate',
    'clothes_06_Leggings',
    'clothes_06_Boots',
    'clothes_07_Helmet',
    'clothes_07_Chestplate',
    'clothes_07_Leggings',
    'clothes_07_Boots',
    'clothes_08_Helmet',
    'clothes_08_Chestplate',
    'clothes_08_Leggings',
    'clothes_08_Boots',
    'clothes_09_Helmet',
    'clothes_09_Chestplate',
    'clothes_09_Leggings',
    'clothes_09_Boots',
    'clothes_10_Helmet',
    'clothes_10_Chestplate',
    'clothes_10_Leggings',
    'clothes_10_Boots',
    'clothes_11_Helmet',
    'clothes_11_Chestplate',
    'clothes_11_Leggings',
    'clothes_11_Boots',
    'clothes_12_Helmet',
    'clothes_12_Chestplate',
    'clothes_12_Leggings',
    'clothes_12_Boots',
    'clothes_13_Helmet',
    'clothes_13_Chestplate',
    'clothes_13_Leggings',
    'clothes_13_Boots',
    'clothes_14_Helmet',
    'clothes_14_Chestplate',
    'clothes_14_Leggings',
    'clothes_14_Boots',
    'clothes_15_Helmet',
    'clothes_15_Chestplate',
    'clothes_15_Leggings',
    'clothes_15_Boots'
]

for name in names:
    args = []
    args.append('name=' + name)

    if name.__contains__('Helmet'):
        args.append('type=itemHelmet')
    if name.__contains__('Boots'):
        args.append('type=itemBoots')
    if name.__contains__('Chestplate'):
        args.append('type=itemChestplate')
    if name.__contains__('Leggings'):
        args.append('type=itemLeggings')

    print('running: java -jar JSONGenerator.jar', *args)
    subprocess.call(['java', '-jar', 'JSONGenerator.jar', *args])
